name: kluster_test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - qgis=3.18.0
  - vispy=0.6.6
  - pyside2=5.13.2
  - gdal=3.2.1
  - h5py
  - pip:
    - sphinx-automodapi
    - sphinx_autodoc_typehints
    - numpydoc
    - git+https://github.com/noaa-ocs-hydrography/drivers.git#egg=hstb.drivers
    - git+https://github.com/noaa-ocs-hydrography/shared.git#egg=hstb.shared
    - git+https://github.com/noaa-ocs-hydrography/vyperdatum.git#egg=vyperdatum
    - git+https://github.com/noaa-ocs-hydrography/bathygrid.git#egg=bathygrid